site_name: Smart Media Documentation
docs_dir: docs
nav:
    - Home: index.md
    - Test: test.md
    - "UU i Smart Media": universell-utforming.md
markdown_extensions:
    - toc:
        baselevel: 2
        toc_depth: "1-2"
theme: readthedocs

